'use client';
import { useState } from 'react';
import { toast } from 'sonner';
import { SimplePage } from '@/components/marketing/SimplePage';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input, Label, Textarea, Select } from '@/components/ui/Input';
import { api } from '@/lib/api';
export default function Page(){const [loading,setLoading]=useState(false); async function submit(e: React.FormEvent<HTMLFormElement>){e.preventDefault(); setLoading(true); const form=new FormData(e.currentTarget); try{await api('/contact',{method:'POST',auth:false,body:JSON.stringify(Object.fromEntries(form))}); toast.success('تم إرسال طلبك بنجاح'); (e.target as HTMLFormElement).reset();}catch(err:any){toast.error(err.message)}finally{setLoading(false)}} return <SimplePage eyebrow="تواصل" title="احجز عرضاً سريعاً لرقابة" description="اترك معلوماتك وسنساعدك على اختيار الإعداد المناسب لمتجرك."><div className="grid gap-6 lg:grid-cols-[1fr_.8fr]"><Card><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><div><Label>الاسم</Label><Input name="name" required/></div><div><Label>الهاتف</Label><Input name="phone" required/></div><div><Label>البريد</Label><Input name="email" type="email"/></div><div><Label>نوع النشاط</Label><Select name="businessType"><option>ملابس</option><option>عطور وتجميل</option><option>إلكترونيات</option><option>صيدلية</option><option>آخر</option></Select></div><div className="md:col-span-2"><Label>الرسالة</Label><Textarea name="message" required defaultValue="أريد تجربة رقابة كلاود لمتجري."/></div><Button disabled={loading} className="md:col-span-2">إرسال الطلب</Button></form></Card><Card className="bg-ink text-white"><h3 className="text-2xl font-black">دعم عربي مباشر</h3><p className="mt-4 leading-8 text-blue-100">يمكنك أيضاً التواصل عبر واتساب لطلب عرض مخصص، استيراد بيانات، أو إعداد موظفين.</p><a href="https://wa.me/213550000000" className="mt-6 inline-flex rounded-2xl bg-white px-5 py-3 font-black text-ink">فتح واتساب</a></Card></div></SimplePage>}
