'use client';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { api } from '@/lib/api';
import { Card } from '@/components/ui/Card';
import { Input, Label, Select } from '@/components/ui/Input';
import { Button } from '@/components/ui/Button';
import { PageHeader } from '@/components/dashboard/PageHeader';
import { Modal } from '@/components/dashboard/Modal';
export default function Staff(){const [rows,setRows]=useState<any[]>([]); const [open,setOpen]=useState(false); const [form,setForm]=useState<any>({fullName:'',email:'',phone:'',role:'STAFF',password:''}); async function load(){const r=await api<any>('/users'); setRows(r.data)} useEffect(()=>{load().catch(e=>toast.error(e.message))},[]); async function submit(e:React.FormEvent){e.preventDefault(); try{await api('/users',{method:'POST',body:JSON.stringify(form)}); toast.success('تم إضافة عضو الفريق'); setOpen(false); load()}catch(e:any){toast.error(e.message)}} return <><PageHeader title="الفريق والصلاحيات" description="إدارة المستخدمين وأدوار الوصول." actionLabel="إضافة موظف" onAction={()=>setOpen(true)}/><Card className="overflow-hidden p-0"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-4 text-right">الاسم</th><th className="p-4 text-right">البريد</th><th className="p-4 text-right">الدور</th><th className="p-4 text-right">الحالة</th></tr></thead><tbody>{rows.map(u=><tr key={u.id} className="border-t"><td className="p-4 font-bold">{u.fullName}</td><td className="p-4">{u.email}</td><td className="p-4">{u.role}</td><td className="p-4">{u.isActive?'نشط':'موقوف'}</td></tr>)}</tbody></table></Card><Modal open={open} onClose={()=>setOpen(false)} title="إضافة موظف"><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><div><Label>الاسم</Label><Input value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></div><div><Label>البريد</Label><Input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></div><div><Label>الهاتف</Label><Input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><Label>الدور</Label><Select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="STAFF">موظف</option><option value="CASHIER">كاشير</option><option value="MANAGER">مدير</option></Select></div><div className="md:col-span-2"><Label>كلمة المرور</Label><Input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></div><Button className="md:col-span-2">حفظ</Button></form></Modal></>}
