import { Router } from 'express';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import slugify from 'slugify';
import multer from 'multer';
import { Account, AppwriteException, Client, Databases, ID, Query, Storage, Users } from 'node-appwrite';
import { z } from 'zod';
import { asyncHandler, ApiError } from './utils/errors';

const endpoint = process.env.APPWRITE_ENDPOINT || 'https://cloud.appwrite.io/v1';
const project = process.env.APPWRITE_PROJECT_ID || '';
const apiKey = process.env.APPWRITE_API_KEY || '';
export const DB_ID = process.env.APPWRITE_DATABASE_ID || 'raqaba';
export const BUCKET_ID = process.env.APPWRITE_BUCKET_ID || 'product_images';

const collections = {
  businesses: 'businesses', users: 'profiles', categories: 'categories', products: 'products', movements: 'inventory_movements',
  customers: 'customers', suppliers: 'suppliers', sales: 'sales', purchases: 'purchases', expenses: 'expenses', notifications: 'notifications', audit: 'audit_logs'
} as const;

type Role = 'OWNER'|'MANAGER'|'CASHIER'|'STAFF';
type ReqUser = { id: string; appwriteUserId: string; businessId: string; role: Role; email: string; fullName: string };

declare global { namespace Express { interface Request { appUser?: ReqUser } } }

function adminClient() { return new Client().setEndpoint(endpoint).setProject(project).setKey(apiKey); }
function publicClient() { return new Client().setEndpoint(endpoint).setProject(project); }
const db = () => new Databases(adminClient());
const users = () => new Users(adminClient());
const storage = () => new Storage(adminClient());
const account = () => new Account(publicClient());

const upload = multer({ storage: multer.memoryStorage(), limits: { fileSize: 2 * 1024 * 1024 } });
const signToken = (payload: Omit<ReqUser, 'fullName'>) => jwt.sign(payload, process.env.JWT_SECRET || 'dev-only-secret-change-me', { expiresIn: (process.env.JWT_EXPIRES_IN || '7d') as any } as any);
const parse = (doc: any) => ({ id: doc.$id, businessId: doc.businessId, ...(doc.data ? JSON.parse(doc.data) : {}), $createdAt: doc.$createdAt, $updatedAt: doc.$updatedAt });
const pack = (businessId: string, data: any) => ({ businessId, data: JSON.stringify({ ...data }) });
const now = () => new Date().toISOString();
const money = (v: any) => Number(v || 0);
const int = (v: any) => Number.parseInt(String(v || 0), 10) || 0;

async function list(col: string, businessId: string, limit = 1000) {
  const res = await db().listDocuments(DB_ID, col, [Query.equal('businessId', businessId), Query.limit(limit)]);
  return res.documents.map(parse);
}
async function get(col: string, id: string) { return parse(await db().getDocument(DB_ID, col, id)); }
async function create(col: string, businessId: string, data: any, id = ID.unique()) { const body = { ...data, createdAt: data.createdAt || now(), updatedAt: data.updatedAt || now() }; const payload: any = pack(businessId, body); if (col === collections.users) { payload.appwriteUserId = body.appwriteUserId || ''; payload.email = body.email || ''; payload.role = body.role || 'STAFF'; } return parse(await db().createDocument(DB_ID, col, id, payload)); }
async function update(col: string, id: string, businessId: string, patch: any) { const cur = await get(col, id); const body = { ...cur, ...patch, id: undefined, updatedAt: now() }; const payload: any = pack(businessId, body); if (col === collections.users) { payload.appwriteUserId = body.appwriteUserId || ''; payload.email = body.email || ''; payload.role = body.role || 'STAFF'; } return parse(await db().updateDocument(DB_ID, col, id, payload)); }
async function remove(col: string, id: string) { await db().deleteDocument(DB_ID, col, id); }
async function audit(req: any, action: string, entity: string, entityId?: string, metadata?: any) { if (!req.appUser) return; await create(collections.audit, req.appUser.businessId, { userId: req.appUser.id, action, entity, entityId, metadata, createdAt: now() }).catch(()=>undefined); }

function requireAuth(req: any, _res: any, next: any) {
  try {
    const auth = req.headers.authorization;
    if (!auth?.startsWith('Bearer ')) throw new ApiError(401, 'يجب تسجيل الدخول أولاً');
    const decoded = jwt.verify(auth.slice(7), process.env.JWT_SECRET || 'dev-only-secret-change-me') as any;
    req.appUser = decoded;
    next();
  } catch { next(new ApiError(401, 'جلسة غير صالحة أو منتهية')); }
}
function atLeast(role: Role) { const rank: Record<Role, number> = { STAFF: 1, CASHIER: 2, MANAGER: 3, OWNER: 4 }; return (req: any, _res: any, next: any) => !req.appUser ? next(new ApiError(401,'يجب تسجيل الدخول')) : rank[req.appUser.role] < rank[role] ? next(new ApiError(403,'ليست لديك صلاحية كافية')) : next(); }

function filterQ(rows: any[], q?: string, fields = ['name','phone','email','sku','barcode','brand','invoiceNumber','reference','title']) {
  if (!q) return rows; const s = q.toLowerCase(); return rows.filter(r => fields.some(f => String(r[f] || '').toLowerCase().includes(s)));
}
function page(rows: any[], req: any) { const p = Math.max(1, int(req.query.page || 1)); const l = Math.min(100, Math.max(1, int(req.query.limit || 25))); return { data: rows.slice((p-1)*l, p*l), meta: { total: rows.length, page: p, limit: l } }; }
async function profileByAppwriteUser(appwriteUserId: string) { const res = await db().listDocuments(DB_ID, collections.users, [Query.equal('appwriteUserId', appwriteUserId), Query.limit(1)]); if (res.documents[0]) return parse(res.documents[0]); const all = await db().listDocuments(DB_ID, collections.users, [Query.limit(100)]); return all.documents.map(parse).find((p:any)=>p.appwriteUserId === appwriteUserId) || null; }
async function profileByEmail(email: string) { const res = await db().listDocuments(DB_ID, collections.users, [Query.equal('email', email.toLowerCase()), Query.limit(1)]); if (res.documents[0]) return parse(res.documents[0]); const all = await db().listDocuments(DB_ID, collections.users, [Query.limit(100)]); return all.documents.map(parse).find((p:any)=>String(p.email).toLowerCase() === email.toLowerCase()) || null; }
function safeUser(p: any) { return { id: p.id, businessId: p.businessId, appwriteUserId: p.appwriteUserId, email: p.email, fullName: p.fullName, phone: p.phone, role: p.role, isActive: p.isActive !== false, lastLoginAt: p.lastLoginAt, createdAt: p.createdAt }; }

export function createAppwriteRouter() {
  const router = Router();

  router.get('/health', (_req, res) => res.json({ ok: true, product: 'رقابة كلاود API - Appwrite', database: 'appwrite', time: new Date().toISOString() }));

  router.post('/auth/register', asyncHandler(async (req, res) => {
    const body = z.object({ businessName: z.string().min(2), fullName: z.string().min(2), email: z.string().email(), password: z.string().min(8), phone: z.string().optional(), wilaya: z.string().optional() }).parse(req.body);
    if (await profileByEmail(body.email)) throw new ApiError(409, 'البريد الإلكتروني مستعمل مسبقاً');
    const awUser = await users().create(ID.unique(), body.email.toLowerCase(), undefined, body.password, body.fullName);
    const business = await create(collections.businesses, 'global', { name: body.businessName, slug: slugify(body.businessName, { lower: true, strict: true }) || `business-${Date.now()}`, phone: body.phone, wilaya: body.wilaya || 'الجزائر', currency: 'DZD', language: 'ar', theme: 'blue', taxRate: 0, subscriptionPlan: 'PRO' });
    await db().updateDocument(DB_ID, collections.businesses, business.id, pack(business.id, { ...business, id: undefined }));
    const profile = await create(collections.users, business.id, { appwriteUserId: awUser.$id, email: body.email.toLowerCase(), fullName: body.fullName, phone: body.phone, role: 'OWNER', isActive: true });
    for (const [name, color, icon] of [['ملابس','#2563eb','shirt'],['عطور وتجميل','#06b6d4','sparkles'],['إلكترونيات','#8b5cf6','smartphone'],['إكسسوارات','#f59e0b','gift']]) await create(collections.categories, business.id, { name, color, icon });
    const token = signToken({ id: profile.id, businessId: business.id, appwriteUserId: awUser.$id, role: 'OWNER', email: profile.email });
    res.status(201).json({ token, user: safeUser(profile), business });
  }));

  router.post('/auth/login', asyncHandler(async (req, res) => {
    const body = z.object({ email: z.string().email(), password: z.string().min(1) }).parse(req.body);
    let session: any;
    try { session = await account().createEmailPasswordSession(body.email.toLowerCase(), body.password); } catch { throw new ApiError(401, 'بيانات الدخول غير صحيحة'); }
    const profile = await profileByAppwriteUser(session.userId);
    if (!profile || profile.isActive === false) throw new ApiError(401, 'بيانات الدخول غير صحيحة');
    const business = await get(collections.businesses, profile.businessId);
    await update(collections.users, profile.id, profile.businessId, { lastLoginAt: now() });
    const token = signToken({ id: profile.id, businessId: profile.businessId, appwriteUserId: profile.appwriteUserId, role: profile.role, email: profile.email });
    res.json({ token, user: safeUser({ ...profile, lastLoginAt: now() }), business });
  }));

  router.use(requireAuth);

  router.get('/auth/me', asyncHandler(async (req, res) => { const p = await get(collections.users, req.appUser!.id); const b = await get(collections.businesses, req.appUser!.businessId); res.json({ user: safeUser(p), business: b }); }));
  router.patch('/auth/profile', asyncHandler(async (req, res) => { const schema = z.object({ fullName: z.string().min(2).optional(), phone: z.string().optional().nullable(), password: z.string().min(8).optional() }); const body = schema.parse(req.body); if (body.password) await users().updatePassword(req.appUser!.appwriteUserId, body.password); const p = await update(collections.users, req.appUser!.id, req.appUser!.businessId, { fullName: body.fullName, phone: body.phone }); await audit(req,'UPDATE_PROFILE','User',p.id); res.json({ user: safeUser(p) }); }));
  router.post('/auth/logout', (_req, res) => res.json({ message: 'تم تسجيل الخروج' }));

  router.get('/categories', asyncHandler(async (req, res) => { const cats = await list(collections.categories, req.appUser!.businessId); const products = await list(collections.products, req.appUser!.businessId); res.json({ data: cats.map(c => ({ ...c, _count: { products: products.filter(p=>p.categoryId===c.id && p.status !== 'ARCHIVED').length } })).sort((a,b)=>a.name.localeCompare(b.name)) }); }));
  router.post('/categories', atLeast('MANAGER'), asyncHandler(async (req, res) => { const body = z.object({ name:z.string().min(2), description:z.string().optional().nullable(), color:z.string().default('#2563eb'), icon:z.string().default('box') }).parse(req.body); const d = await create(collections.categories, req.appUser!.businessId, body); await audit(req,'CREATE','Category',d.id,d); res.status(201).json({ data: d }); }));
  router.patch('/categories/:id', atLeast('MANAGER'), asyncHandler(async (req, res) => { const d = await update(collections.categories, req.params.id, req.appUser!.businessId, req.body); await audit(req,'UPDATE','Category',d.id,d); res.json({ data: d }); }));
  router.delete('/categories/:id', atLeast('MANAGER'), asyncHandler(async (req, res) => { await remove(collections.categories, req.params.id); await audit(req,'DELETE','Category',req.params.id); res.status(204).send(); }));

  router.get('/products', asyncHandler(async (req, res) => { const cats = await list(collections.categories, req.appUser!.businessId); let rows = filterQ(await list(collections.products, req.appUser!.businessId), String(req.query.q || '')); rows = rows.filter(p => (req.query.status ? p.status === req.query.status : p.status !== 'ARCHIVED')); if (req.query.categoryId) rows = rows.filter(p=>p.categoryId===req.query.categoryId); if (String(req.query.lowStock||'') === 'true') rows = rows.filter(p=>int(p.stock)<=int(p.lowStockThreshold)); rows = rows.sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))).map(p=>({ ...p, category: cats.find(c=>c.id===p.categoryId) || null })); res.json(page(rows, req)); }));
  router.get('/products/barcode/:code', asyncHandler(async (req, res) => { const rows = await list(collections.products, req.appUser!.businessId); const p = rows.find(x => x.status !== 'ARCHIVED' && (x.barcode === req.params.code || x.sku === req.params.code)); if (!p) throw new ApiError(404,'لم يتم العثور على المنتج'); res.json({ data: p }); }));
  router.post('/products/upload', atLeast('MANAGER'), upload.single('image'), asyncHandler(async (req, res) => { if (!req.file) throw new ApiError(400,'لم يتم رفع صورة'); const file = await storage().createFile(BUCKET_ID, ID.unique(), { name: req.file.originalname, type: req.file.mimetype, size: req.file.size, arrayBuffer: async()=>req.file!.buffer } as any); res.status(201).json({ url: `${endpoint}/storage/buckets/${BUCKET_ID}/files/${file.$id}/view?project=${project}` }); }));
  router.post('/products', atLeast('MANAGER'), asyncHandler(async (req, res) => { const body = z.object({ name:z.string().min(2), sku:z.string().min(1), barcode:z.string().optional().nullable(), brand:z.string().optional().nullable(), categoryId:z.string().optional().nullable(), imageUrl:z.string().optional().nullable(), description:z.string().optional().nullable(), price:z.coerce.number(), cost:z.coerce.number(), stock:z.coerce.number().int().min(0).default(0), lowStockThreshold:z.coerce.number().int().min(0).default(5), status:z.string().default('ACTIVE') }).parse(req.body); const p = await create(collections.products, req.appUser!.businessId, body); if (p.stock > 0) await create(collections.movements, req.appUser!.businessId, { productId:p.id, userId:req.appUser!.id, type:'STOCK_IN', quantity:p.stock, previousStock:0, newStock:p.stock, reason:'رصيد افتتاحي' }); await audit(req,'CREATE','Product',p.id,p); res.status(201).json({ data:p }); }));
  router.patch('/products/:id', atLeast('MANAGER'), asyncHandler(async (req, res) => { const cur = await get(collections.products, req.params.id); const patch = { ...req.body }; if (patch.price !== undefined) patch.price = money(patch.price); if (patch.cost !== undefined) patch.cost = money(patch.cost); if (patch.stock !== undefined) patch.stock = int(patch.stock); const p = await update(collections.products, req.params.id, req.appUser!.businessId, patch); if (patch.stock !== undefined && patch.stock !== cur.stock) await create(collections.movements, req.appUser!.businessId, { productId:p.id, userId:req.appUser!.id, type:'ADJUSTMENT', quantity:patch.stock-cur.stock, previousStock:cur.stock, newStock:patch.stock, reason:'تعديل يدوي للمخزون' }); await audit(req,'UPDATE','Product',p.id,patch); res.json({ data:p }); }));
  router.delete('/products/:id', atLeast('MANAGER'), asyncHandler(async (req, res) => { const p = await update(collections.products, req.params.id, req.appUser!.businessId, { status:'ARCHIVED' }); await audit(req,'ARCHIVE','Product',p.id); res.json({ data:p }); }));
  router.post('/products/:id/movements', atLeast('MANAGER'), asyncHandler(async (req, res) => { const body = z.object({ type:z.enum(['STOCK_IN','STOCK_OUT','ADJUSTMENT']), quantity:z.coerce.number().int(), reason:z.string().optional(), note:z.string().optional() }).parse(req.body); const p = await get(collections.products, req.params.id); const newStock = body.type === 'ADJUSTMENT' ? body.quantity : int(p.stock) + (body.type === 'STOCK_IN' ? body.quantity : -body.quantity); if (newStock < 0) throw new ApiError(400,'لا يمكن أن يصبح المخزون سالباً'); await update(collections.products, p.id, req.appUser!.businessId, { stock:newStock }); const m = await create(collections.movements, req.appUser!.businessId, { productId:p.id, userId:req.appUser!.id, type:body.type, quantity: body.type === 'STOCK_OUT' ? -Math.abs(body.quantity) : body.quantity, previousStock:p.stock, newStock, reason:body.reason, note:body.note }); await audit(req,'STOCK_MOVEMENT','Product',p.id,m); res.status(201).json({ data:m }); }));

  function people(kind: 'customers'|'suppliers') { const col = kind === 'customers' ? collections.customers : collections.suppliers; router.get(`/${kind}`, asyncHandler(async (req, res) => { const rows = filterQ(await list(col, req.appUser!.businessId), String(req.query.q || '')).sort((a,b)=>String(b.updatedAt||'').localeCompare(String(a.updatedAt||''))); res.json(page(rows, req)); })); router.get(`/${kind}/:id`, asyncHandler(async (req,res)=>{ const d=await get(col,req.params.id); const history = kind==='customers' ? (await list(collections.sales, req.appUser!.businessId)).filter(s=>s.customerId===d.id) : (await list(collections.purchases, req.appUser!.businessId)).filter(p=>p.supplierId===d.id); res.json({ data: { ...d, [kind==='customers'?'sales':'purchases']: history } }); })); router.post(`/${kind}`, atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const d=await create(col, req.appUser!.businessId, req.body); await audit(req,'CREATE',kind==='customers'?'Customer':'Supplier',d.id,d); res.status(201).json({ data:d }); })); router.patch(`/${kind}/:id`, atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const d=await update(col, req.params.id, req.appUser!.businessId, req.body); await audit(req,'UPDATE',kind==='customers'?'Customer':'Supplier',d.id,d); res.json({ data:d }); })); router.delete(`/${kind}/:id`, atLeast('MANAGER'), asyncHandler(async (req,res)=>{ await remove(col,req.params.id); await audit(req,'DELETE',kind==='customers'?'Customer':'Supplier',req.params.id); res.status(204).send(); })); }
  people('customers'); people('suppliers');

  router.get('/inventory/movements', asyncHandler(async (req,res)=>{ const products=await list(collections.products, req.appUser!.businessId); let rows=await list(collections.movements, req.appUser!.businessId); if(req.query.productId) rows=rows.filter(m=>m.productId===req.query.productId); if(req.query.type) rows=rows.filter(m=>m.type===req.query.type); rows=rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(m=>({ ...m, product: products.find(p=>p.id===m.productId), user: { fullName: '' } })); res.json(page(rows, req)); }));
  router.get('/inventory/low-stock', asyncHandler(async (req,res)=>{ const rows=(await list(collections.products, req.appUser!.businessId)).filter(p=>p.status!=='ARCHIVED' && int(p.stock)<=int(p.lowStockThreshold)).sort((a,b)=>int(a.stock)-int(b.stock)); res.json({ data: rows }); }));
  router.get('/inventory/valuation', asyncHandler(async (req,res)=>{ const rows=(await list(collections.products, req.appUser!.businessId)).filter(p=>p.status!=='ARCHIVED'); const costValue=rows.reduce((s,p)=>s+money(p.cost)*int(p.stock),0); const retailValue=rows.reduce((s,p)=>s+money(p.price)*int(p.stock),0); res.json({ data: { skuCount: rows.length, units: rows.reduce((s,p)=>s+int(p.stock),0), costValue, retailValue, potentialMargin: retailValue-costValue } }); }));

  router.get('/sales', asyncHandler(async (req,res)=>{ const customers=await list(collections.customers, req.appUser!.businessId); const products=await list(collections.products, req.appUser!.businessId); let rows=filterQ(await list(collections.sales, req.appUser!.businessId), String(req.query.q||''), ['invoiceNumber']); rows=rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(s=>({ ...s, customer: customers.find(c=>c.id===s.customerId)||null, items: (s.items||[]).map((i:any)=>({ ...i, product: products.find(p=>p.id===i.productId) })) })); res.json(page(rows, req)); }));
  router.post('/sales', asyncHandler(async (req,res)=>{ const body=z.object({ customerId:z.string().optional().nullable(), items:z.array(z.object({ productId:z.string(), quantity:z.coerce.number().int().positive(), unitPrice:z.coerce.number().optional(), discount:z.coerce.number().default(0) })).min(1), discount:z.coerce.number().default(0), tax:z.coerce.number().default(0), paymentMethod:z.string().default('CASH'), note:z.string().optional().nullable() }).parse(req.body); const products=await list(collections.products, req.appUser!.businessId); const by=new Map(products.map(p=>[p.id,p])); const items=body.items.map(i=>{ const p=by.get(i.productId); if(!p) throw new ApiError(404,'بعض المنتجات غير موجودة'); if(int(p.stock)<i.quantity) throw new ApiError(400,`المخزون غير كافٍ للمنتج: ${p.name}`); const unitPrice=i.unitPrice ?? money(p.price); return { productId:p.id, quantity:i.quantity, unitPrice, cost:money(p.cost), discount:i.discount, total:Math.max(0, unitPrice*i.quantity-i.discount) }; }); const subtotal=items.reduce((s,i)=>s+i.total,0); const total=Math.max(0, subtotal-body.discount+body.tax); const count=(await list(collections.sales, req.appUser!.businessId)).length; const invoiceNumber=`RC-${new Date().getFullYear()}-${String(count+1).padStart(5,'0')}`; const sale=await create(collections.sales, req.appUser!.businessId, { customerId:body.customerId, userId:req.appUser!.id, invoiceNumber, subtotal, discount:body.discount, tax:body.tax, total, paymentMethod:body.paymentMethod, status:'COMPLETED', note:body.note, items }); for (const i of items) { const p=by.get(i.productId)!; const newStock=int(p.stock)-i.quantity; await update(collections.products, p.id, req.appUser!.businessId, { stock:newStock }); await create(collections.movements, req.appUser!.businessId, { productId:p.id, userId:req.appUser!.id, type:'SALE', quantity:-i.quantity, previousStock:p.stock, newStock, referenceType:'Sale', referenceId:sale.id, reason:`بيع ${invoiceNumber}` }); if(newStock<=int(p.lowStockThreshold)) await create(collections.notifications, req.appUser!.businessId, { type:'LOW_STOCK', title:'تنبيه مخزون منخفض', message:`${p.name} وصل إلى ${newStock} قطعة`, readAt:null }); } if(body.customerId){ const c=await get(collections.customers,body.customerId); await update(collections.customers,c.id,req.appUser!.businessId,{ totalSpent:money(c.totalSpent)+total }); } await create(collections.notifications, req.appUser!.businessId, { type:'SALE_CREATED', title:'عملية بيع جديدة', message:`${invoiceNumber} بقيمة ${total.toLocaleString('fr-DZ')} دج`, readAt:null }); await audit(req,'CREATE','Sale',sale.id,{total}); res.status(201).json({ data:sale }); }));
  router.get('/sales/:id', asyncHandler(async (req,res)=>{ const s=await get(collections.sales,req.params.id); const customers=await list(collections.customers, req.appUser!.businessId); const products=await list(collections.products, req.appUser!.businessId); const business=await get(collections.businesses, req.appUser!.businessId); res.json({ data: { ...s, customer: customers.find(c=>c.id===s.customerId)||null, business, items:(s.items||[]).map((i:any)=>({ ...i, product:products.find(p=>p.id===i.productId) })) } }); }));
  router.get('/sales/:id/receipt', asyncHandler(async (req,res)=>{ const s=await get(collections.sales,req.params.id); const products=await list(collections.products, req.appUser!.businessId); const customer=s.customerId ? await get(collections.customers,s.customerId).catch(()=>null) : null; const business=await get(collections.businesses,req.appUser!.businessId); res.json({ data: { ...s, business, customer, items:(s.items||[]).map((i:any)=>({ ...i, product:products.find(p=>p.id===i.productId) })), qrPayload:`SALE:${s.invoiceNumber}:${s.total}` } }); }));
  router.patch('/sales/:id/cancel', asyncHandler(async (req,res)=>{ const s=await get(collections.sales,req.params.id); if(s.status==='CANCELLED') throw new ApiError(400,'الفاتورة ملغاة مسبقاً'); for(const i of s.items||[]){ const p=await get(collections.products,i.productId); const newStock=int(p.stock)+int(i.quantity); await update(collections.products,p.id,req.appUser!.businessId,{ stock:newStock }); await create(collections.movements,req.appUser!.businessId,{ productId:p.id,userId:req.appUser!.id,type:'RETURN',quantity:int(i.quantity),previousStock:p.stock,newStock,referenceType:'Sale',referenceId:s.id,reason:'إلغاء عملية بيع' }); } const u=await update(collections.sales,s.id,req.appUser!.businessId,{ status:'CANCELLED' }); await audit(req,'CANCEL','Sale',s.id); res.json({ data:u }); }));

  router.get('/purchases', asyncHandler(async (req,res)=>{ const suppliers=await list(collections.suppliers,req.appUser!.businessId); const products=await list(collections.products,req.appUser!.businessId); let rows=filterQ(await list(collections.purchases,req.appUser!.businessId),String(req.query.q||''),['reference']); rows=rows.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(p=>({ ...p, supplier:suppliers.find(s=>s.id===p.supplierId)||null, items:(p.items||[]).map((i:any)=>({ ...i, product:products.find(p=>p.id===i.productId) })) })); res.json(page(rows, req)); }));
  router.post('/purchases', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const body=z.object({ supplierId:z.string().optional().nullable(), items:z.array(z.object({ productId:z.string(), quantity:z.coerce.number().int().positive(), unitCost:z.coerce.number() })).min(1), shippingCost:z.coerce.number().default(0), status:z.string().default('RECEIVED'), note:z.string().optional().nullable() }).parse(req.body); const products=await list(collections.products,req.appUser!.businessId); const by=new Map(products.map(p=>[p.id,p])); const items=body.items.map(i=>({ ...i,total:i.quantity*i.unitCost })); const subtotal=items.reduce((s,i)=>s+i.total,0); const count=(await list(collections.purchases,req.appUser!.businessId)).length; const reference=`PO-${new Date().getFullYear()}-${String(count+1).padStart(5,'0')}`; const purchase=await create(collections.purchases,req.appUser!.businessId,{ supplierId:body.supplierId, userId:req.appUser!.id, reference, subtotal, shippingCost:body.shippingCost, total:subtotal+body.shippingCost, status:body.status, receivedAt:body.status==='RECEIVED'?now():null, note:body.note, items }); if(body.status==='RECEIVED'){ for(const i of items){ const p=by.get(i.productId); if(!p) continue; const newStock=int(p.stock)+i.quantity; await update(collections.products,p.id,req.appUser!.businessId,{ stock:newStock, cost:i.unitCost }); await create(collections.movements,req.appUser!.businessId,{ productId:p.id,userId:req.appUser!.id,type:'PURCHASE',quantity:i.quantity,previousStock:p.stock,newStock,referenceType:'Purchase',referenceId:purchase.id,reason:`استلام شراء ${reference}` }); } } await audit(req,'CREATE','Purchase',purchase.id,{total:purchase.total}); res.status(201).json({ data:purchase }); }));

  router.get('/expenses', asyncHandler(async (req,res)=>{ let rows=filterQ(await list(collections.expenses,req.appUser!.businessId), String(req.query.q||''), ['title']); if(req.query.category) rows=rows.filter(e=>e.category===req.query.category); rows=rows.sort((a,b)=>String(b.paidAt||b.createdAt).localeCompare(String(a.paidAt||a.createdAt))); res.json(page(rows, req)); }));
  router.post('/expenses', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const d=await create(collections.expenses,req.appUser!.businessId,{ ...req.body, amount:money(req.body.amount), paidAt:req.body.paidAt || now() }); await audit(req,'CREATE','Expense',d.id,d); res.status(201).json({ data:d }); }));
  router.patch('/expenses/:id', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const d=await update(collections.expenses,req.params.id,req.appUser!.businessId,{ ...req.body, amount:req.body.amount!==undefined?money(req.body.amount):undefined }); await audit(req,'UPDATE','Expense',d.id,d); res.json({ data:d }); }));
  router.delete('/expenses/:id', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ await remove(collections.expenses,req.params.id); await audit(req,'DELETE','Expense',req.params.id); res.status(204).send(); }));

  router.get('/reports/summary', asyncHandler(async (req,res)=>{ const days=Math.min(365,Math.max(1,int(req.query.days||30))); const from=new Date(); from.setDate(from.getDate()-days); const sales=(await list(collections.sales,req.appUser!.businessId)).filter(s=>s.status==='COMPLETED' && new Date(s.createdAt)>=from); const expenses=(await list(collections.expenses,req.appUser!.businessId)).filter(e=>new Date(e.paidAt||e.createdAt)>=from); const products=(await list(collections.products,req.appUser!.businessId)).filter(p=>p.status!=='ARCHIVED'); const customers=(await list(collections.customers,req.appUser!.businessId)).length; const movements=(await list(collections.movements,req.appUser!.businessId)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,10).map(m=>({ ...m, product:products.find(p=>p.id===m.productId) })); const revenue=sales.reduce((s,x)=>s+money(x.total),0); const profit=sales.reduce((s,x)=>s+(x.items||[]).reduce((a:any,i:any)=>a+(money(i.unitPrice)-money(i.cost))*int(i.quantity)-money(i.discount),0),0)-expenses.reduce((s,e)=>s+money(e.amount),0); const trend=new Map<string,any>(); for(let i=days-1;i>=0;i--){ const d=new Date(); d.setDate(d.getDate()-i); const key=d.toISOString().slice(0,10); trend.set(key,{date:key,revenue:0,orders:0}); } sales.forEach(s=>{ const k=String(s.createdAt).slice(0,10); const d=trend.get(k); if(d){d.revenue+=money(s.total); d.orders++;} }); const best=new Map<string,any>(); const cats=await list(collections.categories,req.appUser!.businessId); const catMap=new Map<string,any>(); for(const sale of sales) for(const item of sale.items||[]){ const p=products.find(x=>x.id===item.productId); if(!p) continue; const b=best.get(p.id)||{id:p.id,name:p.name,sku:p.sku,quantity:0,revenue:0}; b.quantity+=int(item.quantity); b.revenue+=money(item.total); best.set(p.id,b); const cn=cats.find(c=>c.id===p.categoryId)?.name||'بدون تصنيف'; const c=catMap.get(cn)||{name:cn,revenue:0,quantity:0}; c.revenue+=money(item.total); c.quantity+=int(item.quantity); catMap.set(cn,c); } const low=products.filter(p=>int(p.stock)<=int(p.lowStockThreshold)); res.json({ data:{ kpis:{ revenue, profit, orders:sales.length, unitsSold:sales.reduce((s,x)=>s+(x.items||[]).reduce((a:any,i:any)=>a+int(i.quantity),0),0), customers, inventoryValue:products.reduce((s,p)=>s+money(p.cost)*int(p.stock),0), lowStockCount:low.length, expenses:expenses.reduce((s,e)=>s+money(e.amount),0) }, revenueTrend:Array.from(trend.values()), bestSellingProducts:Array.from(best.values()).sort((a,b)=>b.quantity-a.quantity).slice(0,8), topCategories:Array.from(catMap.values()).sort((a,b)=>b.revenue-a.revenue).slice(0,8), lowStock:low.slice(0,12), recentActivity:movements } }); }));
  router.get('/reports/export/sales.csv', asyncHandler(async (req,res)=>{ const sales=await list(collections.sales,req.appUser!.businessId); res.setHeader('Content-Type','text/csv; charset=utf-8'); res.setHeader('Content-Disposition','attachment; filename="sales.csv"'); res.send(['invoiceNumber,date,total,paymentMethod,status',...sales.map(s=>[s.invoiceNumber,s.createdAt,s.total,s.paymentMethod,s.status].join(','))].join('\n')); }));

  router.get('/users', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const rows=(await list(collections.users,req.appUser!.businessId)).map(safeUser); res.json({ data: rows }); }));
  router.post('/users', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const body=z.object({ fullName:z.string().min(2), email:z.string().email(), phone:z.string().optional().nullable(), role:z.string().default('STAFF'), password:z.string().min(8).optional(), isActive:z.boolean().optional() }).parse(req.body); const aw=await users().create(ID.unique(),body.email.toLowerCase(),undefined,body.password||'ChangeMe123!',body.fullName); const p=await create(collections.users,req.appUser!.businessId,{ appwriteUserId:aw.$id,email:body.email.toLowerCase(),fullName:body.fullName,phone:body.phone,role:body.role,isActive:body.isActive??true }); await audit(req,'CREATE','User',p.id,{role:p.role}); res.status(201).json({ data:safeUser(p), temporaryPassword:body.password?undefined:'ChangeMe123!' }); }));
  router.patch('/users/:id', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const cur=await get(collections.users,req.params.id); if(req.body.password) await users().updatePassword(cur.appwriteUserId,req.body.password); const p=await update(collections.users,req.params.id,req.appUser!.businessId,{ ...req.body, password:undefined }); await audit(req,'UPDATE','User',p.id,req.body); res.json({ data:safeUser(p) }); }));

  router.get('/settings', asyncHandler(async (req,res)=>{ res.json({ data: await get(collections.businesses,req.appUser!.businessId) }); }));
  router.patch('/settings', atLeast('MANAGER'), asyncHandler(async (req,res)=>{ const d=await update(collections.businesses,req.appUser!.businessId,req.appUser!.businessId,req.body); await audit(req,'UPDATE','Business',d.id,d); res.json({ data:d }); }));
  router.get('/notifications', asyncHandler(async (req,res)=>{ const rows=(await list(collections.notifications,req.appUser!.businessId)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,50); res.json({ data: rows }); }));
  router.patch('/notifications/:id/read', asyncHandler(async (req,res)=>{ const d=await update(collections.notifications,req.params.id,req.appUser!.businessId,{ readAt:now() }); res.json({ data:d }); }));
  router.get('/audit-logs', asyncHandler(async (req,res)=>{ const usersList=await list(collections.users,req.appUser!.businessId); const rows=(await list(collections.audit,req.appUser!.businessId)).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).slice(0,100).map(a=>({ ...a, user: usersList.find(u=>u.id===a.userId) || null })); res.json({ data: rows }); }));
  return router;
}

export async function ensureAppwriteSchema() {
  if (!project || !apiKey) throw new Error('APPWRITE_PROJECT_ID and APPWRITE_API_KEY are required');
  const databases = db();
  async function ignore(fn:()=>Promise<any>) { try { return await fn(); } catch(e:any) { if (e?.code === 409 || e?.type?.includes('already_exists')) return null; throw e; } }
  await ignore(()=>databases.create(DB_ID, 'Raqaba Cloud'));
  for (const col of Object.values(collections)) {
    await ignore(()=>databases.createCollection(DB_ID, col, col, [], false, true));
    await ignore(()=>databases.createStringAttribute(DB_ID, col, 'businessId', 128, false));
    await ignore(()=>databases.createStringAttribute(DB_ID, col, 'data', 60000, false));
    if (col === collections.users) {
      await ignore(()=>databases.createStringAttribute(DB_ID, col, 'appwriteUserId', 128, false));
      await ignore(()=>databases.createStringAttribute(DB_ID, col, 'email', 255, false));
      await ignore(()=>databases.createStringAttribute(DB_ID, col, 'role', 32, false));
    }
  }
  await new Promise(r=>setTimeout(r, 6000));
  for (const col of Object.values(collections)) await ignore(()=>databases.createIndex(DB_ID, col, 'businessId_idx', 'key' as any, ['businessId']));
  await ignore(()=>databases.createIndex(DB_ID, collections.users, 'appwriteUserId_idx', 'key' as any, ['appwriteUserId']));
  await ignore(()=>databases.createIndex(DB_ID, collections.users, 'email_idx', 'key' as any, ['email']));
  await ignore(()=>storage().createBucket(BUCKET_ID, 'Product Images', [], false, true, 2 * 1024 * 1024, ['jpg','jpeg','png','webp','gif']));
}

export async function seedAppwrite() {
  await ensureAppwriteSchema();
  const existing = await db().listDocuments(DB_ID, collections.users, [Query.equal('email','owner@raqaba.dz'), Query.limit(1)]);
  if (existing.total) { console.log('Appwrite seed already exists'); return; }
  let owner: any, manager: any, cashier: any;
  for (const [email,name] of [['owner@raqaba.dz','أمين بن يوسف'],['manager@raqaba.dz','سارة مراد'],['cashier@raqaba.dz','ليلى منصوري']]) {
    const u = await users().create(ID.unique(), email, undefined, 'DemoPass123!', name);
    if (email.startsWith('owner')) owner = u; if (email.startsWith('manager')) manager = u; if (email.startsWith('cashier')) cashier = u;
  }
  const business = await create(collections.businesses, 'global', { name:'متجر النخبة الجزائر', slug:'elite-alger', phone:'0550 12 34 56', address:'حي الأعمال، الجزائر العاصمة', wilaya:'الجزائر', currency:'DZD', language:'ar', theme:'blue', taxRate:0, subscriptionPlan:'PRO' });
  await db().updateDocument(DB_ID, collections.businesses, business.id, pack(business.id, { ...business, id: undefined }));
  await create(collections.users,business.id,{ appwriteUserId:owner.$id,email:'owner@raqaba.dz',fullName:'أمين بن يوسف',phone:'0550 00 00 01',role:'OWNER',isActive:true });
  await create(collections.users,business.id,{ appwriteUserId:manager.$id,email:'manager@raqaba.dz',fullName:'سارة مراد',phone:'0550 00 00 02',role:'MANAGER',isActive:true });
  await create(collections.users,business.id,{ appwriteUserId:cashier.$id,email:'cashier@raqaba.dz',fullName:'ليلى منصوري',phone:'0550 00 00 03',role:'CASHIER',isActive:true });
  const catDefs=[['ملابس','#2563eb','shirt'],['عطور وتجميل','#06b6d4','sparkles'],['إلكترونيات','#8b5cf6','smartphone'],['هدايا وإكسسوارات','#f59e0b','gift'],['صيدلية','#10b981','heart-pulse']];
  const cats=[] as any[]; for(const [name,color,icon] of catDefs) cats.push(await create(collections.categories,business.id,{name,color,icon}));
  const productData:any[]=[['قميص قطني رجالي Premium','CL-TSH-001','613100000001','Atlas Wear',0,2900,1450,42,8],['فستان نسائي سهرة أزرق','CL-DRS-002','613100000002','Mode DZ',0,7800,4200,12,4],['عطر Oud Royal 50ml','BE-PRF-101','613100000101','Nour',1,6200,3100,18,5],['كريم عناية بالبشرة Argan','BE-SKN-130','613100000130','Sahara Beauty',1,1800,900,7,10],['سماعات Bluetooth Pro','EL-AUD-221','613100000221','TechNova',2,5400,3300,24,6],['شاحن سريع USB-C 30W','EL-CHR-044','613100000044','DZ Power',2,2200,1150,55,12],['ساعة ذكية Fit DZ','EL-WCH-310','613100000310','TechNova',2,12500,8500,9,3],['علبة هدايا فاخرة','GF-BOX-011','613100000011','Giftline',3,950,420,80,15],['محفظة جلدية رجالية','AC-WAL-087','613100000087','Tlemcen Leather',3,3500,1800,16,5],['ميزان حرارة رقمي','PH-THR-009','613100000009','MediCare',4,1650,950,6,8]];
  const products=[] as any[]; for(const p of productData){ const pr=await create(collections.products,business.id,{ name:p[0],sku:p[1],barcode:p[2],brand:p[3],categoryId:cats[p[4]].id,price:p[5],cost:p[6],stock:p[7],lowStockThreshold:p[8],status:'ACTIVE',description:'منتج تجريبي واقعي لإظهار لوحة التحكم.' }); products.push(pr); await create(collections.movements,business.id,{ productId:pr.id,userId:owner.$id,type:'STOCK_IN',quantity:pr.stock,previousStock:0,newStock:pr.stock,reason:'رصيد افتتاحي من بيانات التجربة' }); }
  const customers=[] as any[]; for(const c of [['نوال قاسمي','0555 24 31 90','باب الزوار'],['رياض حمادي','0661 98 44 10','القبة'],['مريم شريف','0770 11 56 30','وهران']]) customers.push(await create(collections.customers,business.id,{ name:c[0],phone:c[1],address:c[2],totalSpent:0 }));
  const suppliers=[] as any[]; for(const s of [['توزيع الجزائر الكبرى','كمال','021 77 11 20','الحراش'],['Beauty Import DZ','سليم','0558 20 20 20','سطيف']]) suppliers.push(await create(collections.suppliers,business.id,{ name:s[0],contact:s[1],phone:s[2],address:s[3] }));
  async function sale(dayOffset:number, ci:number, idxs:number[]){ const date=new Date(); date.setDate(date.getDate()-dayOffset); const items=idxs.map(idx=>({ productId:products[idx].id, quantity:idx%2+1, unitPrice:products[idx].price, cost:products[idx].cost, discount:0, total:products[idx].price*(idx%2+1) })); const subtotal=items.reduce((s,i)=>s+i.total,0); const discount=subtotal>10000?500:0; const total=subtotal-discount; const doc=await create(collections.sales,business.id,{ customerId:customers[ci].id,userId:cashier.$id,invoiceNumber:`RC-2026-${String(dayOffset+1).padStart(5,'0')}`,subtotal,discount,tax:0,total,paymentMethod:dayOffset%3===0?'BARIDIMOB':'CASH',status:'COMPLETED',items,createdAt:date.toISOString() }); for(const i of items){ const p=products.find(p=>p.id===i.productId); p.stock-=i.quantity; await update(collections.products,p.id,business.id,{ stock:p.stock }); await create(collections.movements,business.id,{ productId:p.id,userId:cashier.$id,type:'SALE',quantity:-i.quantity,previousStock:p.stock+i.quantity,newStock:p.stock,referenceType:'Sale',referenceId:doc.id,reason:`بيع ${doc.invoiceNumber}`,createdAt:date.toISOString() }); } const c=customers[ci]; c.totalSpent=(c.totalSpent||0)+total; await update(collections.customers,c.id,business.id,{ totalSpent:c.totalSpent }); }
  await sale(0,0,[0,2,7]); await sale(1,1,[4,5]); await sale(3,2,[1,8]); await sale(5,0,[2,3,7]); await sale(9,1,[6]); await sale(12,2,[0,5,8]);
  await create(collections.purchases,business.id,{ supplierId:suppliers[0].id,userId:manager.$id,reference:'PO-2026-00001',subtotal:86000,shippingCost:3000,total:89000,status:'RECEIVED',receivedAt:now(),items:[{productId:products[0].id,quantity:20,unitCost:1450,total:29000},{productId:products[5].id,quantity:50,unitCost:1150,total:57500}] });
  await create(collections.expenses,business.id,{ title:'إيجار المحل',category:'RENT',amount:65000,paidAt:new Date(Date.now()-5*86400000).toISOString() });
  await create(collections.expenses,business.id,{ title:'حملة إعلانات فيسبوك',category:'MARKETING',amount:12000,paidAt:new Date(Date.now()-2*86400000).toISOString() });
  await create(collections.expenses,business.id,{ title:'نقل البضاعة',category:'TRANSPORT',amount:4500,paidAt:new Date(Date.now()-1*86400000).toISOString() });
  await create(collections.notifications,business.id,{ type:'SYSTEM',title:'مرحباً بك في رقابة',message:'تم تجهيز بيانات Appwrite تجريبية واقعية لتبدأ الاستكشاف.',readAt:null });
  await create(collections.notifications,business.id,{ type:'LOW_STOCK',title:'منتج يحتاج إعادة طلب',message:'كريم عناية بالبشرة قريب من حد المخزون المنخفض.',readAt:null });
  console.log('Appwrite seed complete: owner@raqaba.dz / DemoPass123!');
}
