'use client';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useState } from 'react';
import { toast } from 'sonner';
import { authApi, setToken } from '@/lib/api';
import { Button } from './ui/Button';
import { Input, Label } from './ui/Input';

export function LoginForm(){const router=useRouter(); const [loading,setLoading]=useState(false); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); setLoading(true); const f=new FormData(e.currentTarget); try{const res=await authApi.login(String(f.get('email')),String(f.get('password'))); setToken(res.token); toast.success('مرحباً بك في رقابة'); router.push('/dashboard')}catch(err:any){toast.error(err.message)}finally{setLoading(false)}} return <form onSubmit={submit} className="space-y-4"><div><Label>البريد الإلكتروني</Label><Input name="email" type="email" defaultValue="owner@raqaba.dz" required/></div><div><Label>كلمة المرور</Label><Input name="password" type="password" defaultValue="DemoPass123!" required/></div><Button disabled={loading} className="w-full">دخول إلى اللوحة</Button><p className="text-center text-sm text-slate-500">لا تملك حساباً؟ <Link href="/register" className="font-bold text-raqaba-700">أنشئ حساباً</Link></p></form>}
export function RegisterForm(){const router=useRouter(); const [loading,setLoading]=useState(false); async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault(); setLoading(true); const payload=Object.fromEntries(new FormData(e.currentTarget)); try{const res=await authApi.register(payload); setToken(res.token); toast.success('تم إنشاء حسابك'); router.push('/dashboard')}catch(err:any){toast.error(err.message)}finally{setLoading(false)}} return <form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><div><Label>اسم المتجر</Label><Input name="businessName" required/></div><div><Label>اسمك</Label><Input name="fullName" required/></div><div><Label>البريد</Label><Input name="email" type="email" required/></div><div><Label>الهاتف</Label><Input name="phone" required/></div><div><Label>الولاية</Label><Input name="wilaya" defaultValue="الجزائر"/></div><div><Label>كلمة المرور</Label><Input name="password" type="password" minLength={8} required/></div><Button disabled={loading} className="md:col-span-2">إنشاء الحساب وفتح اللوحة</Button><p className="text-center text-sm text-slate-500 md:col-span-2">لديك حساب؟ <Link href="/login" className="font-bold text-raqaba-700">تسجيل الدخول</Link></p></form>}
