'use client';
import { useEffect, useState } from 'react';
import { toast } from 'sonner';
import { api } from '@/lib/api';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Input, Label, Select } from '@/components/ui/Input';
import { PageHeader } from '@/components/dashboard/PageHeader';
export default function Settings(){const [form,setForm]=useState<any>({}); useEffect(()=>{api<any>('/settings').then(r=>setForm(r.data))},[]); async function submit(e:React.FormEvent){e.preventDefault(); try{const r=await api<any>('/settings',{method:'PATCH',body:JSON.stringify(form)}); setForm(r.data); toast.success('تم تحديث الإعدادات')}catch(e:any){toast.error(e.message)}} return <><PageHeader title="الإعدادات" description="معلومات النشاط، العملة، اللغة والتنبيهات."/><Card><form onSubmit={submit} className="grid gap-4 md:grid-cols-2"><div><Label>اسم النشاط</Label><Input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></div><div><Label>الهاتف</Label><Input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></div><div><Label>الولاية</Label><Input value={form.wilaya||''} onChange={e=>setForm({...form,wilaya:e.target.value})}/></div><div><Label>العملة</Label><Select value={form.currency||'DZD'} onChange={e=>setForm({...form,currency:e.target.value})}><option value="DZD">دينار جزائري</option><option value="EUR">Euro</option></Select></div><div><Label>اللغة</Label><Select value={form.language||'ar'} onChange={e=>setForm({...form,language:e.target.value})}><option value="ar">العربية</option><option value="fr">Français</option></Select></div><div><Label>نسبة الضريبة %</Label><Input type="number" value={form.taxRate||0} onChange={e=>setForm({...form,taxRate:Number(e.target.value)})}/></div><div className="md:col-span-2"><Label>العنوان</Label><Input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></div><Button className="md:col-span-2">حفظ الإعدادات</Button></form></Card></>}
